version: '3'
services: 
    kong:
        image: kong:2.4-alpine
        container_name: kong
        environment: 
            KONG_DATABASE: cassandra
            KONG_CASSANDRA_CONTACT_POINTS: kong-database
            KONG_PROXY_ACCESS_LOG: /dev/stdout
            KONG_ADMIN_ACCESS_LOG: /dev/stdout
            KONG_PROXY_ERROR_LOG: /dev/stderr
            KONG_ADMIN_ERROR_LOG: /dev/stderr
            KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
            KONG_LUA_SSL_TRUSTED_CERTIFICATE: /etc/ssl/certs/ca-certificates.crt
        ports: 
            - 80:8000
            - 443:8443
            - 127.0.0.1:8001:8001
#            - 8444:8444
        restart: always
        depends_on: 
            - cassandra
    
    cassandra:
        image: cassandra:3.11.10
        container_name: kong-database
        ports: 
            - 127.0.0.1:7000:7000
        restart: always
        volumes: 
            - ./cassandra-vol:/var/lib/cassandra

    konga:
        image: pantsel/konga
        container_name: konga
        environment: 
            NODE_ENV: production
            TOKEN_SECRET: ${TOKEN_SECRET}
        restart: always
        ports: 
            - 1337:1337
        volumes: 
            - ./konga-vol:/app/kongadata
